name: outclass
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: 3.3.8

dependencies:
  animations: ^2.0.7
  auto_route: ^5.0.4
  bloc: ^8.1.0
  cross_file: ^0.3.3+2
  desktop_drop: ^0.4.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dynamic_color: ^1.5.4
  equatable: ^2.0.5
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.0.8
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^6.2.0
  flutter_staggered_grid_view: ^0.6.2
  form_builder_validators: ^8.4.0
  fresh_dio: ^0.3.2
  get_it: ^7.2.0
  hydrated_bloc: ^9.0.0
  infinite_scroll_pagination: ^3.2.0
  injectable: ^2.1.0
  intl: ^0.17.0
  material_design_icons_flutter: ^6.0.7096
  open_app_file: ^4.0.1
  path_provider: ^2.0.11
  pretty_qr_code: ^2.0.3
  syncfusion_flutter_calendar: ^20.4.48

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  injectable_generator: ^2.1.2
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
